### PR TITLE
Create network-ee:stable-2.9-latest image

### PR DESCRIPTION
**Pull request by pabelanger**
Bring online the ability to create stable-2.9 images too.

Depends-On: https://github.com/ansible/ansible-builder/pull/167
Depends-On: https://github.com/ansible/network-ee/pull/18
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 62aed1fe3f20aafe92c9a80c5132c7041ba29ebd

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now b8694e5424e57cd9023527023846bb4ccf8b744a

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 167ca6d0a6eb182eeab9e86e411cc6391fcb9cd2

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now e703933a45062a2f77b7b34a13bffc1d5d26ef0e

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 3d63e5968f5938e12d6962cfb0e2ca14a470eaac

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 7384990e89ec45251ccd13b0e13a18f3c7cf6dfb

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now e2cc39587bc70a7fcb5f9889a8747cc72b4f4951

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now d57e6c63cc6c1d9a756c56e96fc88bc8418df92c

**Review by AlanCoding — APPROVED** [review]
thanks for updating, this is exciting and I look forward to testing this pattern with AWX

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 8e91369bac07a9f06e79126cc76ecb5a0cacdf0e

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 663940f275d06cabb2ac058f98c097b83bae7921

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 55d0a389e1451a7acae3b12f1cedd9fa48571419

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 7032a430fbc58a7223f565a73c8fe7a51902f001

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 85f422b76e945b358d5fd00de2a7da1c64b4304f

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 77beaf12100ccaf48664720b365a47f950471399

**Pull request merged**
