### PR TITLE
update requirements with ansible.network collection entry

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
Depends-On: https://github.com/ansible/project-config/pull/808

### CODE REVIEW

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by pabelanger** [comment]
you need to run
```
tox -ebuild
```
locally, to generate the _build folder changes.

**Comment by rohitthakur2590** [comment]
> you need to run
> 
> ```
> tox -ebuild
> ```
> 
> locally, to generate the _build folder changes.

I have updated the _build changes. Thank you

**Comment by trishnaguha** [comment]
Looks like the tests have passed now. Can this be merged now? @rohitthakur2590 @pabelanger @GomathiselviS

**Comment by rohitthakur2590** [comment]
> Looks like the tests have passed now. Can this be merged now? @rohitthakur2590 @pabelanger @GomathiselviS

Let's wait on @pabelanger  approval and access to Merge.

**Pull request merged**
