### PR TITLE
PR to add security supported collection to EE

### PR DESCRIPTION
**Pull request by justjais**
PR to add security supported collection to EE

Depends-On: https://review.opendev.org/c/zuul/zuul-jobs/+/797909
Depends-On: https://review.opendev.org/c/zuul/zuul-jobs/+/798000

### CODE REVIEW

**Comment by justjais** [comment]
cc @pabelanger

**Comment by justjais** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by justjais** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
@justjais okay, we need to close this PR and create a new one. We cannot clear old status checks, which we no longer need.

**Comment by pabelanger** [comment]
https://github.com/ansible/network-ee/pull/89

**Pull request closed without merging**
