### PR TITLE
Pin Pytest 6.2.0

### PR DESCRIPTION
**Pull request by Akasurde**
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by Akasurde** [comment]
See failure here - https://ansible.softwarefactory-project.io/zuul/build/c90f0abbee0341b28cbf1d856ed9c970

**Review by goneri — APPROVED** [review]

**Comment by goneri** [comment]
This will be reversed as soon as a fixed pytest is released.

**Comment by Akasurde** [comment]
recheck

**Comment by goneri** [comment]
@Akasurde I'm migrating the network-ee collection to SF, this way we will be able to land the PR. The CI configuration if this project is a bit complicated.

**Comment by alinabuzachis** [comment]
recheck

**Comment by goneri** [comment]
Closing, we've got https://github.com/ansible/network-ee/commit/26604d4836aade226f60f07727776b4eb0c0b092 merged now.

**Pull request closed without merging**
